//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignupWithLoginMvc.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int Id { get; set; }
       
        [DisplayName("First Name")]   //Data annotation
        [Required(ErrorMessage = "First name is required field")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name is required field")]
        public string lastName { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required field")]
        public string gender { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is required field")]
        public int age { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required field")]
        [RegularExpression("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$",ErrorMessage ="Invalid Email")]
        public string email { get; set; }

        [DisplayName("UserName")]
        [Required(ErrorMessage = "Username is required field")]
        public string username { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Password is required field")] 
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "Confirm Password is required field")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage ="Password is not identical")]
        public string confirm_password { get; set; }
    }
}
